### ISSUE TITLE
Is this library still being developed?

### ISSUE THREAD

**Issue by RebinX1** [frzi/Model3DView#5]

**Comment by frzi** [comment]
Not directly, no. 😄  Due to not working with SwiftUI lately this package hasn't gotten much attention from me. And with the introduction of Apple's visionOS it feels like we're this close to seeing [`Model3D`](https://developer.apple.com/documentation/realitykit/model3d/) arrive to iOS and such. Which'll probably have much better support and features as it gets older.

Impossible to tell when (or if) this package will see continued development again. But it should still work pretty well out-of-the-box for very basic 3D needs in a SwiftUI app!
