### ISSUE TITLE
How to setting flash light effect

### ISSUE THREAD

**Issue by abinhho** [frzi/Model3DView#7]
Thank you for your hard work.

I can see 3D model does not have any bright/dark effect when I rotate them. I want to have effect like a flash light from my eye to 3D model. 
How can I do that.

**Comment by frzi** [comment]
Interesting concept! There were plans to add scene compositing features to add lights et al in the beginning. But due to feature creep and the vast amount of work it required I decided to hold off on such features and release a MVP for now.

Sadly, right now, to achieve the effect you want is gonna require a bit of work:
1) Create (or find) an environment HDRI with the lighting baked. Something like [here](https://polyhaven.com/hdris/studio).
2) Set the HDRI via the [`.ibl()`](https://github.com/frzi/swiftui-model3dview?tab=readme-ov-file#skybox-and-ibl-image-based-lighting) view modifier.
3) Add pan/touch gestures that rotate the 3D model. The rotation can be applied via [`.transform()`](https://github.com/frzi/swiftui-model3dview?tab=readme-ov-file#transform) view modifier.

This should create a similar effect. Best of luck! 😄

**Comment by abinhho** [comment]
@frzi Thank you for answering.

**Comment by abinhho** [comment]
I tried to change a lot of parameters but no luck.

```
struct ContentView: View {
    @State var camera = PerspectiveCamera()
    
    var body: some View {
        Model3DView(named: "Duck.gltf")
            .transform(
                rotate: Euler(x: -camera.rotation.x, y: -camera.rotation.y, z: -camera.rotation.z),
                scale: 1,
                translate: [0, 0, 0]
            )
            .ibl(named: "brown_photostudio_02_1k.hdr", intensity: 1.0)
            .frame(width: 200, height: 200)
            .cameraControls(OrbitControls(
                    camera: $camera,
                    sensitivity: 0.5,
                    minPitch: .degrees(0),
                    maxPitch: .degrees(0),
                    minZoom: 2,
                    maxZoom: 2,
                    friction: 0.1
                ))
    }
}

```
