### ISSUE TITLE
Depending on the asset's origin, they may not be centered correctly by default.

### ISSUE THREAD

**Issue by abinhho** [frzi/Model3DView#9]
This is a known issue, but I am facing it. Which parameter I can adjust to make it center?

**Comment by frzi** [comment]
This can indeed be annoying. But it's by design. By respecting the model's origin, artists have more control over how the model can be animated and manipulated when transforming it.

A parameter or a setting to change a model's origin would be interesting. But it'd require a bit of rewrite of the current code 😅 Though I'll definitely keep it in mind for a potential future update!

If you're the creator of the model you could try editing the model yourself in the 3D modelling software and change its origin.

Alternatively you can experiment with some transform values (as tedious as it may be)

**Comment by abinhho** [comment]
Let me try. Thank you.
